name: EcCommandsShop
version: 1.0.0
api: 4.0.0
main: EnderChestCommand\EnderChestCommandMain
author: BabyGurlLike
    
commands:
  ec:
    usage: /ec
    description: ouvrir son enderchest
    permission: ec.use
permissions:
  ec.use:
    default: op
